name: positive_num
description: >-
  An implementation of immutable value objects PositiveInt and PositiveDouble
  that encapsulate a positive number of type int or double.
version: 2.0.1
repository: https://github.com/maxeema/positive_num

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
