name: positive_num
description: >-
  The package contains a value object PositiveNum
  that encapsulates a positive number which
  can have int or double.
  An PositiveNum instance guarantees that it holds
  a positive number, otherwise it can't be instantiated.
version: 1.0.7+1
repository: https://github.com/maxeema/positive_num

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
