name: positive_num
description: >-
  The package contains an immutable value object
  called PositiveNum that encapsulates a positive number
  (any number greater than 0) which can be int or double.
  PositiveNum guarantees that its value is always positive
  and can't be change after creation.
  PositiveNum can't be created with 0 or negative value.
version: 1.0.7+1
repository: https://github.com/maxeema/positive_num

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
